### ISSUE TITLE
Breaking Bedrock Not working Fabric 1.21

### ISSUE THREAD

**Issue by MamboGamesStudios** [AnAwesomGuy/breakingbedrock#1]
Unfortunately the mod "Breaking Bedrock" does not allow me to open minecraft using Fabric 1.21.
 
The game return me this:
 
The game crashed whilst bootstrap
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2246 failed

**Comment by AnAwesomGuy** [comment]
i have not ported to 1.21 yet, currently doing it
